name: Merge Queue

on:
  merge_group:

jobs:
  call-daily-tests:
    uses: ./.github/workflows/daily.yml
    with:
      skipjobs: "valgrind,macos"
      skiptests: ""
      test_args: ""
      cluster_test_args: ""
      use_repo: "Merge-Queue-Test-For-Valkey/merge-queue-test"
      use_git_ref: "unstable"
